version: 0.2

phases:
  install:
    commands:
      # Install dependencies
      - npm install --prefix server && npm install --prefix clients/orgchart && npm install --prefix clients/mainpage && npm install --prefix clients/contract

      # Upgrade AWS CLI
      - pip install --upgrade awscli
