export default {
  email: "ejay.gharat.79z@gmaiil.us",
  name: "Tamzin Wilkinson",
  title: "general manager",
  manager: "",
  children: [
    {
      email: "lsashiniiddamalgm@lccweb.org",
      name: "Federico Reyna",
      title: "department manager",
      manager: "Tamzin Wilkinson",
      children: [
        {
          email: "msraviteja990@bellaserababy.com",
          name: "Mahira Herrera",
          title: "department manager",
          manager: "Federico Reyna",
          children: [
            {
              email: "hmohamed@360.band",
              name: "Anaya Carr",
              title: "senior engineer",
              manager: "Mahira Herrera",
              children: [],
              id: "oc-9c44ee35-6b38-4c88-8c65-09c699762a2d",
            },
          ],
          id: "oc-80c32e1d-3f71-4971-a3c2-65caab55e4be",
        },
        {
          email: "hjeffreysoanj@guiwoallam.cf",
          name: "Burhan Stevens",
          title: "department manager",
          manager: "Federico Reyna",
          children: [],
          id: "oc-efb81af7-9218-4e5a-97c1-c80521339be2",
        },
      ],
      id: "oc-eef54418-b8b4-49dc-a012-d5369dc3db41",
    },
    {
      email: "tillipyme-2031@yopmail.com",
      name: "Gregg Giles",
      title: "department manager",
      manager: "Tamzin Wilkinson",
      children: [
        {
          email: "prahulwala1@froknowsphoto.org",
          name: "Willa Arellano",
          title: "senior engineer",
          manager: "Gregg Giles",
          children: [
            {
              email: "gmirzasaqibmi@hallsulrics.tk",
              name: "Denny Cameron",
              title: "engineer",
              manager: "Willa Arellano",
              children: [],
              id: "oc-7923a26a-7857-42bf-b851-d9a9793cfed1",
            },
            {
              email: "jacheb.noureddins@llotfourco.tk",
              name: "Hadi Aguilar",
              title: "intern dev",
              manager: "Willa Arellano",
              children: [],
              id: "oc-dde18ad8-f936-4750-b3bc-e1de2494aad4",
            },
          ],
          id: "oc-2bc03ae1-00c4-44a8-afe1-0f19728984d9",
        },
        {
          email: "2joseane8h@gmaiil.us",
          name: "Marilyn Woodard",
          title: "engineer",
          manager: "Gregg Giles",
          children: [],
          id: "oc-efbcc64e-0b9d-4889-93ec-fe524a9711c1",
        },
        {
          email: "6hocine.mistak@xedoiutret.cf",
          name: "Tonya Rees",
          title: "senior engineer",
          manager: "Gregg Giles",
          children: [],
          id: "oc-561f3b58-3ce1-4bc0-bb37-ce1d0265c36b",
        },
      ],
      id: "oc-70ff5c48-cca2-4270-a2f0-f3af3648f8e8",
    },
    {
      email: "lsashiniiddamalgm@lccweb.org",
      name: "Mikolaj Hastings",
      title: "senior engineer",
      manager: "Tamzin Wilkinson",
      children: [],
      id: "oc-8db81cbf-77f6-415e-b6bb-0df5a82261d4",
    },
  ],
  id: "oc-0b0c7fa8-3445-4ad9-9dfc-9a46e5b0b0c5",
};
